### PR TITLE
Adding Kadenze creative coding courses to learning materials section

### PR DESCRIPTION
**Pull request by DexterShepherd**
Great list!

I added a few courses from Kadenze to the Learning Materials section. They all follow a common format so I am submitting as one PR but I can break it out if that is easier for you @terkelg .

If you are happy with this I will keep submitting PRs as we add more creative coding courses to Kadenze to keep the list up to date. 

👍

### CODE REVIEW

**Comment by terkelg** [comment]
Thanks for you contribution @DexterShepherd.
For future requests, please make every addition its own PR.

When that being said, I'm not keen on making this a listening on Kadenze courses.
Kadenze has some really good content, so what about adding a link to the ```creative computing``` category instead of linking every single course?

Thanks

**Comment by terkelg** [comment]
Awesome! 💯

**Comment by DexterShepherd** [comment]
Oops accidentally closed this when I removed the problem commits from my branch. I agree that adding individual courses is not the way to go. I've added a link to the Kadenze Creative Coding page instead. 😀

**Comment by terkelg** [comment]
NP. Really good contribution. I didn't know about Kadenze, but there's some really exiting courses - added a few to my "watch list". Thanks.

**Pull request merged**
