### PR TITLE
Add libossia and qml-creative-controls

### PR DESCRIPTION
**Pull request by jcelerier**
I put them in "other" but maybe there should be a "libraries" part not specific to the web ? 

* libossia allows to control Max, Pd, Unity, OpenFrameworks, Python etc... through a common network interface and multiple protocols (OSC, MIDI, OSCQuery...).
* qml-creative-controls is a UI widget library with controls useful for creative coding : color choosers, joypads, keyboards, etc

### CODE REVIEW

**Comment by terkelg** [comment]
Thanks for the PR @jcelerier.
Can you please explain a bit more what libossia do?

**Comment by jcelerier** [comment]
@terkelg it gives a "standardized" object model to applications that use it (or if the application framework already provides one, it tries to map to it closely).

Then, it makes this object model available through the network, with data types relevant to creative coding (for instance colors and color formats, sound amplitude, etc). 

This makes it very easy to control for instance a part of a PureData patch with OpenFrameworks, Qt, web pages, etc... and also create scores for them with software like i-score, Vézer, Duration...

For instance in Unity3D you'd do : 

    public class MyObject : MonoBehaviour {
        [Ossia.Parameter] 
        int myAttrib;

        [Ossia.Parameter] 
        Color otherAttrib;
    } 

In PureData : 
pd

In QML : 
```
Slider 
{
    id: attackSlider
    Ossia.Binding {
        on:  500 * (180 + parent.value) / 360
        node: '/attack'
    }
}
LineEdit {
    // Maps to the "/text" node
    Ossia.Property on text { }
}
```

and then you can access through websockets and http the list of nodes that are declared. 
For instance with the aforementioned puredata patch, going to http://127.0.0.1:5678 would give the following JSON, which is a description of all the parameters available in the application, their type, range, unit, etc... : 
```
{
  "FULL_PATH": "/",
  "ACCESS": 0,
  "CONTENTS": {
    "modratio": {
      "FULL_PATH": "/modratio",
      "TYPE": "f",
      "VALUE": 4,
      "RANGE": {
        "MIN": 0,
        "MAX": 1
      },
      "ACCESS": 3,
      "CLIPMODE": "None",
      "DEFAULT_VALUE": 4,
      "TAGS": [],
      "PRIORITY": 0,
      "DESCRIPTION": ""
    },
    "note": {
      "FULL_PATH": "/note",
      "TYPE": "ff",
      "VALUE": [
        0,
        0
      ],
      "RANGE": [
        null,
        null
      ],
      "ACCESS": 3,
      "CLIPMODE": "None",
      "TAGS": [],
      "PRIORITY": 0,
      "EXTENDED_TYPE": "vecf",
      "DESCRIPTION": ""
    },
    "attack": {
      "FULL_PATH": "/attack",
      "TYPE": "f",
      "VALUE": 10,
      "RANGE": {
        "MIN": 0,
        "MAX": 1
      },
      "ACCESS": 3,
      "CLIPMODE": "None",
      "DEFAULT_VALUE": 10,
      "TAGS": [],
      "PRIORITY": 0,
      "DESCRIPTION": ""
    },
    "decay": {
      "FULL_PATH": "/decay",
      "TYPE": "f",
      "VALUE": 500,
      "RANGE": {
        "MIN": 0,
        "MAX": 1
      },
      "ACCESS": 3,
      "CLIPMODE": "None",
      "DEFAULT_VALUE": 500,
      "TAGS": [],
      "PRIORITY": 0,
      "DESCRIPTION": ""
    },
    "modgain": {
      "FULL_PATH": "/modgain",
      "TYPE": "f",
      "VALUE": 0,
      "RANGE": {
        "MIN": 0,
        "MAX": 1
      },
      "ACCESS": 3,
      "CLIPMODE": "None",
      "DEFAULT_VALUE": 0,
      "TAGS": [],
      "PRIORITY": 0,
      "DESCRIPTION": ""
    }
  }
}
```

Now, libossia's "client" usage reads and parses this JSON into a mirror tree of objects in the client software, and applies the relevant transformations: for instance if a node is in RGB color and you send an HSL triplet, it is converted and put in the correct range, etc.

**Comment by terkelg** [comment]
Nice work 👍 That's really interesting. 
I'm going to bookmark that for sure, might come in handy later.
I'm not sure it fits the list because it's a little too specific and low level compared to the other tools.

However, I'll consider it if I create a "modules" section or similar, where PR like these fit a bit better.

**Comment by jcelerier** [comment]
no problem! indeed, it's more "building blocks" for applications, rather than high level tools that give results easily.

**Comment by terkelg** [comment]
Thanks for being so understanding! Keep up the good work, high-five 💯

**Pull request closed without merging**
