### PR TITLE
Added 2 new slacks

### PR DESCRIPTION
**Pull request by nucliweb**
Two new Slacks of Creative Coding
- Creative Coding Slack.
- openFrameworks Slack.

### CODE REVIEW

**Comment by terkelg** [comment]
Nice additions. Thanks for helping out with the list 👍

**Comment by terkelg** [comment]
I can't join, because I have no invite. How do people get invited to these? Maybe we should link to the invite page. What do you think?

**Comment by danielvoicu** [comment]
Hi. The codingp5 slack has an invite page over here: http://the-mccc-project.github.io/creative-coding-sign-up/

I've added it a few days ago in another PR, along with a Facebook group.

**Comment by terkelg** [comment]
@danielvoicu thanks, can you maybe submit a PR with only the slack group, where you change the url to the invite page?

If we only have one change/addition per PR 👍

**Comment by nucliweb** [comment]
Ok, thanks ;)

**Pull request merged**
