### PR TITLE
Add a section about web hosting

### PR DESCRIPTION
**Pull request by hangtwenty**
Just an initial take at some web hosting suggestions

---------------------------------------------------------

Not attached to it, feedback welcome, etc 😀

### CODE REVIEW

**Comment by hangtwenty** [comment]
I think the static sites section seems straightforward.

I also added some notes on backend hosting including FaaS. I think these can be great resources for creative coders who want to add backend features.

I've found that folks who aren't working professionally with cloud provider platforms may not know about their options. I tried to convey some of the most useful cheap ways I know about, without too much detail... but I want to make it so somebody wouldn't have to read umpteen Medium posts and analyze too much, before finding their solution :-)

Still, it's wordier than other parts. Happy to move it to a different spot in the doc, split it into a sub page, or just revise. Let me know!

**Comment by terkelg** [comment]
Thanks for the PR! I think hosting is a bit off topic. What do you think?

**Comment by hangtwenty** [comment]
Yeah it would be for many projects but for backend-interactive projects it seems relevant. I need a host for text generation projects for example.

Maybe if web hosting was just one line “If you need web hosting, here are some side-project-ready tips.” and have that just link to another markdown document, either in this repo or not.

Or can be closed ;)

(sent from my phone)

**Comment by hangtwenty** [comment]
I'll close, and re open when it's improved one way or another

**Pull request closed without merging**
