### PR TITLE
NEORT Added to Online Section

### PR DESCRIPTION
**Pull request by gonzarodriguezt**
[NEORT](https://neort.io/popular) - Digital art platform for creative coders, 3DCG creators, animators, illustrators or anybody who creates awesome visual artworks.

### CODE REVIEW

**Comment by gonzarodriguezt** [comment]
@terkelg Please review. 🙏

**Comment by terkelg** [comment]
Hi @gonzarodriguezt. Thank you for the PR. Can you elaborate on what this is? It's kinda like ShaderToy, right?

**Comment by gonzarodriguezt** [comment]
Yes! @terkelg just like ShaderToy, but it also supports Javascript.

**Comment by terkelg** [comment]
Thank you. Can you shorten the description a bit? We're almost there 👍

**Pull request merged**
